# sudo apt update
# sudo apt install nginx -y
# systemctl status nginx

# sudo nano /etc/nginx/sites-available/api-demo.autocycle.dev
# # Paste the following in the file

# sudo ln -s /etc/nginx/sites-available/api-demo.autocycle.dev /etc/nginx/sites-enabled/
# sudo nginx -t
# sudo systemctl restart nginx

# sudo apt install certbot python3-certbot-nginx -y
# sudo certbot --nginx -d api-demo.autocycle.dev


server {
    listen 80;
    server_name api-demo.autocycle.dev;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl http2;
    server_name api-demo.autocycle.dev;

    # SSL Certificates (Certbot)
    ssl_certificate /etc/letsencrypt/live/api-demo.autocycle.dev/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/api-demo.autocycle.dev/privkey.pem;

    # SSL Security
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;

    ###################################################
    # FASTAPI BACKEND (127.0.0.1:8000)
    ###################################################
    location /api/ {
        proxy_pass http://127.0.0.1:8000/;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        proxy_connect_timeout 60s;
        proxy_send_timeout 120s;
        proxy_read_timeout 120s;
        proxy_buffering off;
    }

   
    location /node/ {
        proxy_pass http://127.0.0.1:4000/;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        proxy_connect_timeout 60s;
        proxy_send_timeout 120s;
        proxy_read_timeout 120s;
        proxy_buffering off;
    }
}