# sudo apt update
# sudo apt install supervisor
# sudo nano /etc/supervisor/conf.d/api-demo.autocycle.dev.conf

# copy and paste the following code into the file

# sudo supervisorctl reread
# sudo supervisorctl update

# sudo supervisorctl start fastapi
# sudo supervisorctl status fastapi

# tail -f /var/log/fastapi.out.log
# tail -f /var/log/fastapi.err.log

# Dont forget to seed the database in recycler map by npm run seed and than build the backend by npm run build
# Dont forget to give keys json into the environment variable GOOGLE_APPLICATION_CREDENTIALS

[program:fastapi]
directory=/home/autocycledev/autocycle/backend
command=/home/autocycledev/autocycle/backend/.venv/bin/uvicorn app.main:app --host 127.0.0.1 --port 8000 --workers 2
autostart=true
autorestart=true
stderr_logfile=/var/log/fastapi.err.log
stdout_logfile=/var/log/fastapi.out.log
user=autocycledev
environment=GOOGLE_APPLICATION_CREDENTIALS="/home/autocycledev/autocycle/backend/keys/autocycle-demo.json"

[program:my-node-app]
command=/usr/bin/node dist/server.js
directory=/home/autocycledev/recyclerMap/backend
autostart=true
autorestart=true
startsecs=10
startretries=3
user=autocycledev
stderr_logfile=/var/log/node-app.err.log
stdout_logfile=/var/log/node-app.out.log
environment=NODE_ENV="production",DB_PATH="/home/autocycledev/recyclerMap/backend/src/db/data/recyclers.db"