[project]
name = "playground"
version = "0.1.0"
description = "playground using crewAI"
authors = [{ name = "Your Name", email = "you@example.com" }]
requires-python = ">=3.10,<3.13"
dependencies = [
    "crewai[tools]>=0.118.0,<1.0.0",
    "fastapi>=0.109.0",
    "uvicorn>=0.27.0",
    "pydantic>=2.6.0"
]

[project.scripts]
playground = "playground.main:run"
run_crew = "playground.main:run"
train = "playground.main:train"
replay = "playground.main:replay"
test = "playground.main:test"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.crewai]
type = "crew"
